# Generated by Django 4.2.6 on 2025-05-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='backImage',
            field=models.ImageField(blank=True, null=True, upload_to='orders/back'),
        ),
        migrations.AlterField(
            model_name='request',
            name='design',
            field=models.ImageField(blank=True, null=True, upload_to='designs'),
        ),
        migrations.AlterField(
            model_name='request',
            name='frontImage',
            field=models.ImageField(blank=True, null=True, upload_to='orders/front'),
        ),
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('unseen', 'unseen'), ('seen', 'seen'), ('pending', 'pending'), ('progress', 'progress'), ('finished', 'finished')], default='unseen', max_length=255),
        ),
    ]
