# Generated by Django 4.2.6 on 2025-05-05 00:13

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_request_backimage_alter_request_design_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='order_pictures'),
        ),
        migrations.AlterField(
            model_name='request',
            name='backImage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='design',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='request',
            name='frontImage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
